services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db3:5432/POSTGRES
      - SPRING_DATASOURCE_USERNAME=POSTGRES
      - SPRING_DATASOURCE_PASSWORD=POSTGRES
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_PASSWORD=POSTGRES
      - POSTGRES_USER=POSTGRES
      - POSTGRES_DB=POSTGRES
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "test" ]
      interval: 10s
      timeout: 3s
      retries: 3
  pgadmin:
    image: 'dpage/pgadmin4:8.5'
    container_name: pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '82:80'